# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('askalma', '0002_auto_20170414_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=32)),
            ],
        ),
    ]
